name: Latest stack oveflow activity
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs once a day at 00:00 UTC
permissions:
      contents: write
jobs:
  update-readme-with-stack-overflow:
    name: Update this repo's README with latest activity from StackOverflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "STACKOVERFLOW"
          commit_message: "Updated readme with the latest StackOverflow data"
          feed_list: "https://stackoverflow.com/feeds/user/3466389"
